### ISSUE TITLE
Admin Can Bulk Add Users

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#10]
The idea from this comes from the CAS-specific instance: adding a list of Students that can access the app by NetID.

We should figure out how this could be generalized (sending an invitation to sign up?).

Blocked on #19.

**Comment by orenyk** [comment]
Upload a list of NetIDs

**Comment by orenyk** [comment]
And create users

**Comment by orenyk** [comment]
And pull data from IDR

**Comment by orenyk** [comment]
blocked on #127
