### ISSUE TITLE
Students can add details/comments to Suites

### ISSUE THREAD

**Issue by AlanLiu96** [YaleSTC/vesta#16]
As a user, I'd like to tag rooms and comment on them.

If I was in a room, I'd like to be able to comment on what rooms were like on characteristics that aren't immediately apparent. You can also upload photos of what your suites look like. Ex. "The traffic on Grove Street is always terribly loud at 4am. You don't want this room".

**Comment by esoterik** [comment]
Also, it'd be good if people that lived in the suite could upload photos of it.
