### ISSUE TITLE
Admins should be able to view a summary of the suites in a draw

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/vesta#175]
Child of #167. Admin should be able to:

1. Visit draw page
2. Click link "Add/Edit Suites"
3. View a giant form:
   1. Suites with checkboxes
   2. Suites organized by suite size
   3. Only available suites displayed (or check-able, I guess they could be disabled)
   4. Within suite size, suites organized by whether or not they belong to another draw already
   5. If they belong to a draw, the draw name should be listed
   6. Admins should be able to check/uncheck all within each section (suite size / belonging to draw or not)
4. Click a submit button
5. Profit!

**Comment by orenyk** [comment]
As an alternative, we may split up the giant form into multiple forms, so /draws/:id/suites` will list a suite dashboard (i.e. table of suite size / # of suites included / add/edit button), and then we can add views / routes for `/draws/:id/suites/edit/:suite_size`, so one form for each suite size to make it more digestible.

This should probably all live in the DrawsController unless we want to extract it out...

**Comment by esoterik** [comment]
We should only show available suites in the edit view

**Comment by orenyk** [comment]
![img_20170210_161542](https://cloud.githubusercontent.com/assets/901808/22859519/3ec34fc4-f0ac-11e6-919d-cc3f23292fb9.jpg)

**Comment by orenyk** [comment]
I'm opening a separate issue for the suite summary on the draw show view.

**Comment by orenyk** [comment]
Got a good way through this, will continue tomorrow.

**Comment by orenyk** [comment]
I'm going to split this into 1) creating the suite summary view (basically done) and 2) creating the suite update pages/routes. New issue incoming.
