### ISSUE TITLE
Verify / streamline the student experience

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/vesta#207]
Walk through all student actions (draw navigation (they can see all draws), intent, group stuff, suite selection, room selection).

**Comment by esoterik** [comment]
Add the first name to the nav so they can tell if the preferred name is out of date

**Comment by orenyk** [comment]
Blocked on #330

**Comment by esoterik** [comment]
* [ ] Students in draft draws should not see the draw card on the index

**Comment by esoterik** [comment]
* [ ] Students in draws without deadlines should see some info on the dashboard in the card

**Comment by esoterik** [comment]
* [ ] Students should be able to see a list of their pending memberships

**Comment by esoterik** [comment]
*[ ] During suite selection: show the number of groups in their size that are ahead of them in selection, as well as the list of currently available suites in their group size.
