### ISSUE TITLE
Draw summary tables should include group sizes without suites

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/vesta#278]
In the DrawsController, instead of populating the oversub_report and the group_report based simply on the available suite sizes, we should also include the sizes of all groups in the draw (even if there are no longer available suites left).

**Comment by orenyk** [comment]
This should be trivial after #209 is merged in since that includes the DrawSizesQuery, we'd just have to update the controller logic a bit.

**Comment by orenyk** [comment]
Nvm this is blocked on #224 since that's where DrawSizesQuery ended up.

**Comment by esoterik** [comment]
resolved by #384
