### ISSUE TITLE
[META] Dashboards for Students/Housing Reps/Admins

### ISSUE THREAD

**Issue by AlanLiu96** [YaleSTC/vesta#303]
Feedback from User Testing:

Housing Reps mentioned that they'd like to have these features on the dashboard. I separated them by the groups the suggestions applied to.

All:
- [ ] Deadlines
   - Intent, Group Formation, Draw

Users:
- [ ] Instructions
- [ ] Floorplans
- [ ] Available rooms for current group size

Admin/Housing Rep:
- [ ] Group-less Students, Undeclared Students

**Comment by orenyk** [comment]
So a lot of this information is draw-by-draw - are housing reps assigned to specific class years / draws?

**Comment by AlanLiu96** [comment]
By assignment, I'm not sure if you're referring to being a member of the draw or organizing/managing that draw. The answer though is the same in either case.

@spaceraccoon Correct me if I'm mistaken, but I believe that there are one or two members of the housing committee per draw. (Ex. 2 Sophomores for sophomore draw) 

They would both run the draws they're assigned to and be participants of the draw.

**Comment by orenyk** [comment]
Ok that's more what I was getting at - whether or not housing committee members need to see / help manage more than one draw. @esoterik this might play into our discussion of housing rep permissions in Pundit - we may want to check against their membership in a given draw.

**Comment by orenyk** [comment]
We need to take into account room selection data when present for students and reps. Example here:

```erb
<% if current_user.room.present? %>
  <h1>Your housing information</h1>
  <h3>Suite: <%= @group.suite.number %></h3>
  <h3>Room: <%= @room.number_with_type %></h3>
  <h3>Group: </h3>
  <ul>
    <% @group.members.each do |m| %>
      <li><%= m.full_name %> (<%= m.room.number %>)</li>
    <% end %>
  </ul>
<% else %>
  <h1>Vesta</h1>
<% end %>
```
