### ISSUE TITLE
Clicking on a link with a different HTTP method before JS loads causes problems

### ISSUE THREAD

**Issue by spaceraccoon** [YaleSTC/vesta#312]

**Comment by orenyk** [comment]
Not sure this was the actual issue, but the lock button has the group id duplicated (e.g. `draws/2/groups/2/2/lock`), but only for groups in draws. Also, I can't replicate this locally on `master`.

**Comment by orenyk** [comment]
Ok, still can't replicate this on `master` so I'm going to just close this. Regardless the weird path helper issue will be solved in #332.

**Comment by orenyk** [comment]
Ok, I think this might have to do with trying to lock a group with transfer students in it. I'll re-test on the #332 branch, re-opening for now.

**Comment by orenyk** [comment]
On second thought, this may be related to the fact that we're using a PUT request for locking, but if the JS assets haven't loaded yet then the lock button will simply issue a GET request, which doesn't match any route. This is probably just a slow asset issue, but we can continue to investigate.

**Comment by esoterik** [comment]
We may want to move up our javascript tags / split it up (it's also likely why the navbar formatting sucks at page load).

**Comment by orenyk** [comment]
Ok, first thing is that caching is probably not enabled since it needs to be activated by touching the file `tmp/caching-dev.txt` (as per development.rb).

**Comment by orenyk** [comment]
This may turn out to be a problem with _my_ browser - the site loads much faster in both DEV and PROD in Chrome on the same machine. If that's the case we can just close this issue and I'll deal with my local setup.

**Comment by orenyk** [comment]
CNR by @esoterik, closing.
