### ISSUE TITLE
Align buttons in Building view table

### ISSUE THREAD

**Issue by spaceraccoon** [YaleSTC/vesta#317]

**Comment by orenyk** [comment]
What exactly is this fixing? Is it the fact that the different tables have different column widths? We've had to deal with this in a few other places, it's just a matter of styling each column based on its `data-role` attribute (see [here](https://github.com/YaleSTC/vesta/blob/master/app/assets/stylesheets/_draws.scss) for an example).

**Comment by spaceraccoon** [comment]
Currently working on this issue - it's because in the draw show view,
buttons have a CSS override for button margins set to 0, but not for other
show views where buttons are used.

**Comment by orenyk** [comment]
Why is there an override on that page? Can we get rid of it?

**Comment by spaceraccoon** [comment]
Hmm that was from a previous commit, the default is that buttons have a
margin which makes rows in the table look unaligned. We should probably do
an override for all buttons if we don't want to keep the margins.

On Sat, Mar 4, 2017 at 11:33 PM Oren Kanner <notifications@github.com>
wrote:

Why is there an override on that page? Can we get rid of it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/YaleSTC/vesta/issues/317#issuecomment-284204868>, or mute
the thread

**Comment by spaceraccoon** [comment]
The current override is in the draws scss.

**Comment by orenyk** [comment]
Ohhhh now I remember, that was me 😛. Ok, so this is just for buttons inside of tables, right?

**Comment by spaceraccoon** [comment]
Yep! But since buttons also turn up in the other tables, we have to keep
doing it :( do I make a higher level override?

On Sat, Mar 4, 2017 at 11:43 PM Oren Kanner <notifications@github.com>
wrote:

Ohhhh now I remember, that was me 😛. Ok, so this is just for buttons
inside of tables, right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/YaleSTC/vesta/issues/317#issuecomment-284205174>, or mute
the thread

**Comment by orenyk** [comment]
I'm comfortable adding `td a.button { margin: 0; }` to `application.scss`, at least for pilot.

**Comment by orenyk** [comment]
I'm merging this into #432
