### ISSUE TITLE
Pre-pilot minor UI changes

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/vesta#324]
@thuynganvu, please add a list of all the minor UI changes you'd like to make below, thanks! We'll associate #304 with this issue.

**Comment by orenyk** [comment]
Please also update the nav color :-)

**Comment by orenyk** [comment]
Please also add a link to the Vesta mailing list in the footer. I will supply you with that e-mail shortly.

**Comment by thuynganvu** [comment]
What color do you want the nav to be, or I can choose anything?
Also waiting for the mailing list. :D

**Comment by orenyk** [comment]
Oh man, I never saw this message! The color should be something in the Yale palette at least, maybe even just white with dark blue text (see [here](https://yaleux.github.io/yaleui/styleguide/colors.html) for the palette). The mailing list is vesta-support@yale.edu. Thanks!

**Comment by esoterik** [comment]
* Remove size from all buttons / links where it's obvious which size they refer to (lock buttons in the draw summary table, etc)
* checkboxes on suites edit are currently broken

**Comment by orenyk** [comment]
Fix top padding, also fix duplicate `hr` tags on draw show at the bottom (e-mail actions section needs to be in a conditional?)

**Comment by esoterik** [comment]
ensure back buttons are on the left and proceed buttons are on the right

**Comment by esoterik** [comment]
"occupents"

**Comment by esoterik** [comment]
remove group edit sidebar

**Comment by orenyk** [comment]
remove link to template CSV

**Comment by orenyk** [comment]
remove intent button from users index

**Comment by esoterik** [comment]
remove group leader link in group report

**Comment by orenyk** [comment]
Change policy on suite selection to always be visible for lottery page

**Comment by orenyk** [comment]
Admins only create groups in pre-lottery phase.

**Comment by murphy-ariel** [comment]
Admins shouldn't get the pop up warning that their room assignment is permanent, since they can go back in and change room assignments in the suite selection phase of the draw.

**Comment by murphy-ariel** [comment]
Don't show the disband button if a suite can be assigned.

**Comment by orenyk** [comment]
Blocked on #303
