### ISSUE TITLE
Set up mailer on AWS

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#351]
We will need to figure out the domain situation (talk to Chris / Harry)

**Comment by orenyk** [comment]
Actually, we may be able to use SMTP since I believe our EC2 instances will be behind the firewall. I'll test this out now.

**Comment by orenyk** [comment]
Long story short - we're not actually behind the firewall, so I'm going to set up AWS SES instead for the pilot (if necessary with a custom domain).
