### ISSUE TITLE
Authentication redirects should send you to where you were going

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/vesta#38]
1. visit restricted route
2. get redirected to login page
3. upon successful login, get sent to route in step 1

**Comment by esoterik** [comment]
huh, I think that this works already? I wrote a passing test on branch `38_auth_redirects`

**Comment by orenyk** [comment]
Apparently it work! ~~It's weird because I don't remember this being the case with Reservations, but I could be mistaken~~ nvm, I think we ended up overwriting the `after_sign_on_path` to deal with CAS, so that's something we'll have to bear in mind when we implement #24.
