### ISSUE TITLE
Add Proceeding to Lottery confirmation page

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#382]
Right now, it's too easy to accidentally proceed to lottery phase, and there's no way to go back, so we need an intermediate page that shows:
* The draw summary table (gives us group metrics, inventory metrics, oversubscription metrics)
* The students without groups summary
* Some warning text about what happens if you proceed without resolving oversubscription if there's oversubscription
* A link to the handle oversubscription page if there's oversubscription

**Comment by orenyk** [comment]
blocking this on #224
