### ISSUE TITLE
Students Can Request to Join Groups

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#56]
Blocked on #49

**Comment by esoterik** [comment]
blocking on #81 due to the introduction of Memberships

**Comment by esoterik** [comment]
implementation details:
- Memberships are getting a `status` enum (approved, pending, and invited)
- `group.memberships_count` will become a conditional counter cache that excludes `pending` memberships

**Comment by esoterik** [comment]
okay, running into problems/pain:

The conditional counter cache is fine, BUT with the new statuses on memberships, all auto-created memberships have status `requested` (e.g. memberships created via `group.members << student`). This means that we lose a lot of the syntactic sugar of `has_many :through` 

I think there's other problems, too, but I think a solution to this might be adding separate associations on `Group` for pending memberships. This way minimizes additional callbacks and let's us keep the default membership status as something unconfirmed -- another solution is to just make the default status the accepted/confirmed one, but that feels unsafe to me.

@orenyk, thoughts?

**Comment by orenyk** [comment]
Per phone discussion, we are good to set "confirmed/accepted" as the default as we'll be explicitly creating memberships in all the other situations.
