### ISSUE TITLE
Groups can be Frozen

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#57]
Should be able to be performed by the group leader OR any admin.

Blocked on #49

**Comment by esoterik** [comment]
blocked on #81

**Comment by orenyk** [comment]
@esoterik who/what was this blocked on? Was it #90?

**Comment by esoterik** [comment]
If a leader decides to freeze/lock a group, it must be confirmed by all members. This can be accomplished by adding a `locked` boolean to `Membership` which is set when a single member agrees to freeze a group.

Admins should be able to skip the approve process and lock groups whenever they want as long as they are full.
