### ISSUE TITLE
Anonymize Group Leaders

### ISSUE THREAD

**Issue by AlanLiu96** [YaleSTC/vesta#582]
Someone mentioned to me that it might be better to anonymize the leaders of the groups in order to prevent peer pressure/harassment.

I know this directly conflicts with our other goal of allowing groups of different sizes to find each other to reconfigure. 

Thoughts?

**Comment by esoterik** [comment]
I mean, the group leader is public because they're in charge of the group and have quite a bit of power over what happens in the group (members / suite selection / room assignment are all essentially determined by leaders)

I suppose we could make it visible to only members of the group and admins? I will add this to the user feedback survey to try to gauge if this would be helpful or not.

Also, this would hinder the "find a suite" feature by quite a bit -- it'd be hard to nicely display all members of all groups on a single page, and right now the group leader gives somewhat of an idea of who is in a group / who to ask about joining a suite

**Comment by AlanLiu96** [comment]
Hmm, We'll have to take a look at the feedback and go from there then.
An alternative to either fully anonymizing or publicizing leader names is to
give leaders an option to "advertise" their group. This lets the leads remain
anonymous if they've already settled their groups, while still giving the option
to publicize for more members, in case others are looking for groups to join.
If we were to implement such a feature, it would ideally be in the group
formation process, if the number of invites + leader  < room size.  





On Sun, Apr 9, 2017 11:41 PM, Sydney Young notifications@github.com  wrote:
I mean, the group leader is public because they're in charge of the group and
have quite a bit of power over what happens in the group (members / suite
selection / room assignment are all essentially determined by leaders)

I suppose we could make it visible to only members of the group and admins? I
will add this to the user feedback survey to try to gauge if this would be
helpful or not.

Also, this would hinder the "find a suite" feature by quite a bit -- it'd be
hard to nicely display all members of all groups on a single page, and right now
the group leader gives somewhat of an idea of who is in a group / who to ask
about joining a suite

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Alan LiuYale Class of 2018m: 908-271-9688

**Comment by orenyk** [comment]
I'm skeptical that the group leaders _in draws_ being public providing an avenue for harassment - these processes have almost always had group compositions be public. Adding a whole separate "promotion" feature for groups seems like it's a lot of work / complexity for something that should be handled offline regardless - we _really_ need to be careful about feature creep, and one of the main goals of the application was complete transparency throughout the process, which this restriction would run counter to.

That said, we can wait and see what the survey says, but even if we see some interest we should still tread carefully.

**Comment by esoterik** [comment]
closing due to feedback from deans / housing comms
