### ISSUE TITLE
Hide group locked status to other students

### ISSUE THREAD

**Issue by AlanLiu96** [YaleSTC/vesta#583]
@thuynganvu and I were discussing this earlier. Another user from the Stiles draw also brought it up. 

It was often used in practice as a way to signal/pressure others to leave the doubles/triples etc groups. 

Would it be a better experience to remove locking visibility to other students?
Thoughts?

**Comment by esoterik** [comment]
We should add this to the feedback survey.

We made it public intentionally -- I think it's useful to know when housing groups are committed to trying to get a particular configuration. I'm not sure if we should be concerned about the pressure aspect, actually; it kinda sucks (really the housing process is stressful and we can only do so much), but from conversations with admins this is a way to reduce the amount of oversubscription. 

Also, how much of a difference does seeing a "locked" group vs. a "finalizing" or "full" group make? Would the essentially the same situation happen anyway? I'm not sure how much of a difference it would make.

**Comment by orenyk** [comment]
I 100% think that this should be left public, and if anything we should encourage deans / admins to only "unlock" groups if absolutely necessary. Locking is a commitment to the specific group and size, and is how a group makes a choice about the risk/reward of going for potentially oversubscribed group sizes. Locking early to try and discourage others from creating groups of a specific size should have the cost of preventing that group from reconfiguring in response to changes in the overall draw picture as time goes on.

As I said in #582, one main goal of this app is to promote _transparency_, so I'm really _really_ skeptical about the value of hiding information during draws. As @esoterik said, housing is always going to be stressful, and as long as there is a random element people will have consider some game theory - the only way to remove all stress from the process would be to either not allow students to make _any_ choices (e.g. they get assigned to groups / suites / rooms randomly) or to completely change up the process (e.g. maybe some kind of match process similar to medical residencies) - that goes way above our pay grade.

**Comment by esoterik** [comment]
closing due to feedback from deans / housing comms
