### ISSUE TITLE
Handle group sizes when a suite size becomes unavailable

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#88]
Group sizes are restricted to suite sizes available in the draw at the time of group creation/editing, but those sizes may become unavailable after the group sets its size.

We need to figure out how to handle this situation. I think that an email notification to the affected groups that tells them they have to change their size along with a banner notification for the group leader while signed in would work well.

**Comment by orenyk** [comment]
Does this mean that we'd force such a group to reconfigure before allowing the draw to proceed to the lottery phase? This should also be added to the "oversubscription report" / confirmation page in #104.

**Comment by esoterik** [comment]
We're going to handle this by checking for the situation after each group assignment and automatically disbanding affected groups in other draws.
