### ISSUE TITLE
Students can be invited to join a Group

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/vesta#90]
Similar to #56, invites should contribute to the Group size and can be accepted by the student they are sent to. Students can still only have one membership.

**Comment by esoterik** [comment]
@orenyk while working on this branch I ran into an intermittent failure of the `UngroupedStudentsQuery` with seed 25043. There's a commit on `90_group_invitations` that is the exact state of everything when I hit this failure.

**Comment by esoterik** [comment]
User-membership relation will be changing to `has_many :memberships`, and we'll override `user.group` to return the group that the user has accepted membership to.
