### ISSUE TITLE
Admins can manually create groups outside of draws

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/vesta#93]
This is for exceptional case handling outside of draws, we want them to be able to create ad-hoc groups of students and assign said groups to suites. We can use our existing data models as long as we remove the `validate :draw, presence: true` from groups and then everything else should be fine.

**Comment by orenyk** [comment]
@esoterik is it safe to duplicate the `groups` resource outside of the `draws` resource? In other words, right now we have

```ruby
# config/routes.rb
...
resources :draws do
  resources :groups
end
...
```

but for this issue we'd want to create a group outside of a given draw, so we'd want routes like `/groups/new` as opposed to `/draws/:id/groups/new`. That said we could just modify the `set_draw` before action in `GroupsController` to only set the instance variable if `params[:draw_id]` is present. I don't really like that though.

What about adding a new controller, i.e. `SpecialGroupsController` and using that for the non-nested routes:

```ruby
resources :groups, controller: 'special_groups'
```

That feels safer to me, even if they both are using the same model.

Another thought - what happens if you want to assign an external group to a draw? Are we going to support that process for admins? I feel like that opens up a whole host of validation issues. Also, what if the students added to this group are already in a draw? Any thoughts? Thanks!

**Comment by esoterik** [comment]
Notes from phone call: 

- have a group composed of students not in a draw, therefore the group is also not in a draw && do a null object pattern
- separate controller makes sense
- suite assignment and everything related to this is ADMIN only

**Comment by orenyk** [comment]
Got most of the way there, although this turned out to involve a lot more moving parts than I expected. Currently the service object (SpecialGroupCreator) specs are failing (I believe since the group is no longer valid without a draw but I'm not sure), and there are still issues with the integration spec. That means the null object pattern is pretty much next and then I think we'll need a major refactor to identify areas of consolidation (for example, the two creators are basically identical with the exception of draw handling). Hopefully done tomorrow!

**Comment by orenyk** [comment]
notes to future me - broken specs, what do we do about students already in groups?
